"use strict";(()=>{var e={};e.id=557,e.ids=[557],e.modules={3524:e=>{e.exports=require("@prisma/client")},399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},7650:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>j,patchFetch:()=>A,requestAsyncStorage:()=>$,routeModule:()=>b,serverHooks:()=>x,staticGenerationAsyncStorage:()=>k});var o={};r.r(o),r.d(o,{GET:()=>y,maxDuration:()=>m,runtime:()=>d});var a=r(9303),n=r(8716),i=r(670),s=r(7070),c=r(464),p=r(247),u=r(6927),l=r(9833);let d="nodejs",m=60;async function y(e){if(e.headers.get("authorization")!==`Bearer ${process.env.CRON_SECRET}`)return s.NextResponse.json({error:"Unauthorized"},{status:401});let{searchParams:t}=new URL(e.url);return"alignment"===(t.get("job")||"session")?w():h()}async function h(){let e=10>new Date().getUTCHours()?"London":"New York";try{let{perfMap:t,calEvents:r,errors:o}=await (0,u.md)();if(0===Object.keys(t).length&&0===r.length)return await (0,l.T)(`⚠️ *Elistas — ${e} Alert*

Could not fetch market data automatically.
Errors: ${o.join(", ")}

Open the dashboard to manually enter data:
https://elistas-dashboard.vercel.app`),s.NextResponse.json({ok:!0,message:"Fetch failed — reminder sent",errors:o});let a=await (0,p.S)({mode:"auto",perfMap:t,calendarEvents:r}),n=new Date;n.setUTCHours(0,0,0,0),await c.db.dailyAlert.upsert({where:{date:n},create:{date:n,top3:a.top3,bottom3:a.bottom3,pairs9:a.pairs9,priority1:a.priority1,sentAt:new Date},update:{top3:a.top3,bottom3:a.bottom3,pairs9:a.pairs9,priority1:a.priority1,sentAt:new Date}});try{await f(a)}catch(e){console.error("Hourly snapshot warning:",e)}let i=(0,p.e)(a,e),d=await (0,l.T)(i);return await g(a),s.NextResponse.json({ok:!0,sent:d,session:e,priority:a.priority1?.pair,scoredBy:"claude-ai",fetchErrors:o})}catch(t){return console.error("Session cron error:",t),await (0,l.T)(`❌ *Elistas Cron Error*
${e} scoring failed: ${t}`),s.NextResponse.json({error:"Session cron failed"},{status:500})}}async function w(){try{let{perfMap:e,calEvents:t,errors:r}=await (0,u.md)();if(0===Object.keys(e).length)return s.NextResponse.json({ok:!0,message:"Skipped — no market data",errors:r});let o=await (0,p.S)({mode:"auto",perfMap:e,calendarEvents:t});try{await f(o)}catch(e){console.error("Hourly snapshot warning:",e)}return await g(o),s.NextResponse.json({ok:!0,scoredBy:"claude-ai",fetchErrors:r})}catch(e){return console.error("Alignment cron error:",e),s.NextResponse.json({error:"Alignment cron failed"},{status:500})}}async function g(e){let t=await c.db.trade.findMany({where:{outcome:"Open"}});if(0===t.length)return;let r=new Set(e.top3.map(e=>e.cur)),o=new Set(e.bottom3.map(e=>e.cur)),a=[];for(let e of t){let t=r.has(e.strongCcy),n=o.has(e.weakCcy),i=t&&n?"Green":t||n?"Amber":"Red",s="Green"===i?`${e.strongCcy} still top 3 \xb7 ${e.weakCcy} still bottom 3`:"Red"===i?`${e.strongCcy} dropped out of top 3 AND ${e.weakCcy} left bottom 3`:t?`${e.weakCcy} no longer in bottom 3`:`${e.strongCcy} no longer in top 3`;if(await c.db.tradeAlignment.create({data:{tradeId:e.id,status:i,strongStillTop3:t,weakStillBottom3:n,reason:s}}),"Green"!==i){let t="Red"===i?"\uD83D\uDD34":"\uD83D\uDFE1";a.push(`${t} *${e.pair} ${e.direction}*
${s}
Entry: ${e.entryPrice} \xb7 SL: ${e.slPrice}`)}}if(a.length>0){let t=new Date().toLocaleTimeString("en-GB",{timeZone:"Africa/Lagos",hour:"2-digit",minute:"2-digit"});await (0,l.T)(`⚡ *Elistas — Trade Alignment Alert*
${t} WAT

${a.join("\n\n")}

Top 3: ${e.top3.map(e=>e.cur).join(" \xb7 ")}
Bottom 3: ${e.bottom3.map(e=>e.cur).join(" \xb7 ")}`)}}async function f(e){let t=new Date(36e5*Math.floor(Date.now()/36e5)),r=e.top3.map(e=>e.cur),o=e.bottom3.map(e=>e.cur),a=e.allScores.map(e=>c.db.hourlyScore.upsert({where:{bucket_currency:{bucket:t,currency:e.cur}},create:{bucket:t,currency:e.cur,score:e.score,pricePerf:e.pricePerf||0,top3:r,bottom3:o},update:{score:e.score,pricePerf:e.pricePerf||0,top3:r,bottom3:o}}));await Promise.all(a)}let b=new a.AppRouteRouteModule({definition:{kind:n.x.APP_ROUTE,page:"/api/cron/route",pathname:"/api/cron",filename:"route",bundlePath:"app/api/cron/route"},resolvedPagePath:"/Users/taiwokenny/Documents/Claude/Projects/elistas-dashboard/app/api/cron/route.ts",nextConfigOutput:"",userland:o}),{requestAsyncStorage:$,staticGenerationAsyncStorage:k,serverHooks:x}=b,j="/api/cron/route";function A(){return(0,i.patchFetch)({serverHooks:x,staticGenerationAsyncStorage:k})}}};var t=require("../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),o=t.X(0,[276,972,334],()=>r(7650));module.exports=o})();